[package]
name = "openmander-map"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
geo = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
polars = { workspace = true }
reqwest = { workspace = true }
zip = { workspace = true }
shapefile = { workspace = true }
tempfile = { workspace = true }
flatgeobuf = { workspace = true }
geozero = { workspace = true }
geoarrow = { workspace = true }
geoarrow-array = { workspace = true }
geoarrow-schema = { workspace = true }
geoparquet = { workspace = true }
arrow-array = { workspace = true }
arrow-schema = { workspace = true }
parquet = { workspace = true }
geo-traits = { workspace = true }

openmander-geometry = { path = "../geometry" }
