[package]
name = "openmander-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }

openmander-map = { path = "../map" }
openmander-pack = { path = "../pack" }
openmander-plan = { path = "../plan" }
