[package]
name = "openmander-geom"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
ahash = { workspace = true }
anyhow = { workspace = true }
geo = { workspace = true }
proj4rs = { workspace = true }
rstar = { workspace = true }
smallvec = { workspace = true }
