[package]
name = "openmander-cli"
version = { workspace = true }
edition = { workspace = true }
publish = false

[dependencies]
anyhow = { workspace = true }
clap = { version = "4.0", features = ["derive"] }

openmander = { path = ".." }
