[package]
name = "openmander-cli"
version = { workspace = true }
edition = { workspace = true }
publish = false

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }

openmander = { path = ".." }
