[package]
name = "openmander-partition"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
ndarray = { workspace = true }
rand = { workspace = true }

openmander-graph = { path = "../graph" }
