[package]
name = "openmander-graph"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
ndarray = { workspace = true }
polars = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
shapefile = { workspace = true }
